name: Build and deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Instalar python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"

      - name: Instalar dependencias
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest case_tests.py
