name: Build and deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Instalar python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13.1"

      - name: Instalar dependências
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar e configurar postgresql
        run: |
          sudo apt update
          sudo apt install postgresql-client postgresql-common -y
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          sleep 10
          sudo -u postgres psql -c "CREATE DATABASE data_ufu;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE data_ufu TO postgres;"
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'IssoJ4éL<>CuR4.';"

      - name: Aguardar o PostgreSQL ficar pronto
        run: |
          while ! pg_isready -h localhost -p 5432; do
            echo "Aguardando PostgreSQL..."
            sleep 1
          done

      - name: Run tests
        env:
            DB_USER: postgres
            DB_PASSWORD: "IssoJ4éL<>CuR4." 
            DB_HOST: localhost
            DB_NAME: data_ufu
        run: |
          source .venv/bin/activate
          pytest case_tests.py
