name: Build and deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Instalar python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"

      - name: Instalar dependencias
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Instalar e configurar postgresql
        run: |
          sudo apt update
          sudo apt install postgresql -y
          sudo systemctl start postgresql
          sudo -u postgres psql -c "CREATE DATABASE data_ufu;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE data_ufu TO postgres;"
          
      - name: Run tests
        env:
          DB_USER: postgres
          DB_PASSWORD: ""
          DB_HOST: localhost
          DB_NAME: data_ufu
        run: |
          source .venv/bin/activate
          pytest case_tests.py
