name: Build and deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Instalar python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"  # Escolha a versão do Python desejada

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest case_tests.py
