name: Build and deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.DB_TEST_CONFIG.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_TEST_CONFIG.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_TEST_CONFIG.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Instalar python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Aguardar o PostgreSQL ficar pronto
        run: |
          until pg_isready -h localhost -U postgres -p 5432; do
            echo "Aguardando PostgreSQL..."
            sleep 1
          done

      - name: Run tests
        env:
          DB_USER: ${{ secrets.DB_TEST_CONFIG.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_TEST_CONFIG.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_TEST_CONFIG.DB_HOST }}
          DB_NAME: ${{ secrets.DB_TEST_CONFIG.DB_NAME }}
        run: |
          . .venv/bin/activate
          python -m pytest case_tests.py
