name: Build and deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Instalar python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13.1"

      - name: Instalar dependências
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar e configurar postgresql
        run: |
          sudo apt update
          sudo apt install postgresql-client postgresql-common -y
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          sleep 10
          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_NAME }} OWNER ${{ secrets.DB_USER }};"
          sudo -u postgres psql -c "ALTER USER ${{ secrets.DB_USER }} WITH PASSWORD '${{ secrets.DB_PASSWORD }}';"

      - name: Aguardar o PostgreSQL ficar pronto
        run: |
          while ! pg_isready -h localhost -p 5432; do
            echo "Aguardando PostgreSQL..."
            sleep 1
          done

      - name: Run tests
        env:
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          source .venv/bin/activate
          pytest case_tests.py
